name: Main Pipeline with FixBot Trigger

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      error_message: ${{ steps.capture-error.outputs.error }}
    steps:
      - name: Step 1
        run: echo "Step 1 done"

      - name: Step 2 (simulate failure)
        id: fail
        continue-on-error: true
        run: |
          echo "Simulating error"
          echo "::error file=test.py,line=1::Something broke"
          exit 1

      - name: Capture Error
        id: capture-error
        if: steps.fail.outcome == 'failure'
        run: |
          echo "error=Step 2 failed: Something broke" >> $GITHUB_OUTPUT

  trigger-fixbot:
    needs: main
    if: needs.main.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger FixBot Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: run-ai-script.yml
          repo: ${{ github.repository }}
          ref: main
          inputs:
            error_message: ${{ needs.main.outputs.error_message }}
        secrets: inherit
