name: Simple AutoFixer Pipeline

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install huggingface_hub

      - name: Simulate Step (May Fail)
        id: test-step
        continue-on-error: true
        run: |
          > error.txt
          echo "haii" 2>>error.txt
          echo "Simulating a failure..." 2>>error.txt 
          echo "::error file=main.py,line=1::Example error message" 2>>error.txt 
          cat kdjwefke.txt 2>>error.txt 

      - name: Run AutoFixer
        if: steps.test-step.outcome == 'failure'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python autoFixer.py
