name: Simple AutoFixer Pipeline

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install huggingface_hub

      - name: Simulate Step (May Fail)
        id: test-step
        continue-on-error: true
        run: |
          echo "Simulating a failure..."
          echo "::error file=main.py,line=1::Example error message"
          cat kdjwefke.txt

      - name: Capture Error Message
        if: steps.test-step.outcome == 'failure'
        run: |
          echo "Step failed. Saving error message..."
          echo "Traceback (most recent call last):\n  File \"main.py\", line 1, in <module>\n    raise Exception('Something broke')" > error.txt

      - name: Run AutoFixer
        if: steps.test-step.outcome == 'failure'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python autoFixer.py
